// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAniXQRoSsJjEoC5UhQ4dfSlBPyPiulpIE',
    appId: '1:766422064173:web:0acffd53b969d00f312ca4',
    messagingSenderId: '766422064173',
    projectId: 'auth-firebase-7030a',
    authDomain: 'auth-firebase-7030a.firebaseapp.com',
    storageBucket: 'auth-firebase-7030a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBlX9qiurhI-1FlGH0jyX4C20KIHvpmnI',
    appId: '1:766422064173:android:917e2dd9755217b7312ca4',
    messagingSenderId: '766422064173',
    projectId: 'auth-firebase-7030a',
    storageBucket: 'auth-firebase-7030a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUfVwQwR91sKlaCYNQec3DZPaLRL5Z0ac',
    appId: '1:766422064173:ios:e3a07568539af6d8312ca4',
    messagingSenderId: '766422064173',
    projectId: 'auth-firebase-7030a',
    storageBucket: 'auth-firebase-7030a.appspot.com',
    iosClientId: '766422064173-omdfkjnicsebc7jnl960m9l2chru0nt7.apps.googleusercontent.com',
    iosBundleId: 'com.example.authFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUfVwQwR91sKlaCYNQec3DZPaLRL5Z0ac',
    appId: '1:766422064173:ios:e3a07568539af6d8312ca4',
    messagingSenderId: '766422064173',
    projectId: 'auth-firebase-7030a',
    storageBucket: 'auth-firebase-7030a.appspot.com',
    iosClientId: '766422064173-omdfkjnicsebc7jnl960m9l2chru0nt7.apps.googleusercontent.com',
    iosBundleId: 'com.example.authFirebase',
  );
}
